### ISSUE TITLE
Composer stability error with beta version of Sylius

### ISSUE THREAD

**Issue by ghost** [Lakion/SyliusElasticSearchBundle#20]
While trying to install the bundle with Sylius 1.0.0 beta version I'm getting the below error:

```
 Problem 1
     - Installation request for lakion/sylius-elastic-search-bundle dev-master -> satisfiable by lakion/sylius-elastic-search-bundle[dev-master].
     - lakion/sylius-elastic-search-bundle dev-master requires sylius/sylius dev-master -> satisfiable by sylius/sylius[dev-master] but these conflict with your requirements or minimum-stability.
```

Is it possible to use this bundle with the current beta version of framework?

**Comment by pjedrzejewski** [comment]
@pearlwithbanana This bundle is compatible only with dev-master right now. We will release it together with beta2 in February.

**Comment by ghost** [comment]
@pjedrzejewski, thanks for your answer. Can't wait! :)

**Comment by igorjacon** [comment]
Has this been fixed? I'm also getting the same error while trying to install this bundle with sylius beta version.
